// Generated by tools/generate-gus-catalog.mjs from catalog/gus-models.json. Do not edit.
package io.github.dannybaanks.isymotron;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public final class GusCatalog {
    private GusCatalog() {}

    public static final class Model {
        public final String id, name, repository, filename, revision, url, sha256, licenseName, licenseUrl, attribution;
        public final long byteCount;
        public Model(String id, String name, String repository, String filename, String revision, String url, long byteCount, String sha256, String licenseName, String licenseUrl, String attribution) {
            this.id = id; this.name = name; this.repository = repository; this.filename = filename; this.revision = revision; this.url = url; this.byteCount = byteCount; this.sha256 = sha256; this.licenseName = licenseName; this.licenseUrl = licenseUrl; this.attribution = attribution;
        }
    }

    private static final List<Model> MODELS = Collections.unmodifiableList(Arrays.asList(
        new Model("qwen25-05b-q4km", "Qwen2.5-0.5B-Instruct · Q4_K_M", "Qwen/Qwen2.5-0.5B-Instruct-GGUF", "qwen2.5-0.5b-instruct-q4_k_m.gguf", "9217f5db79a29953eb74d5343926648285ec7e67", "https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/9217f5db79a29953eb74d5343926648285ec7e67/qwen2.5-0.5b-instruct-q4_k_m.gguf", 491400032L, "74a4da8c9fdbcd15bd1f6d01d621410d31c6fc00986f5eb687824e7b93d7a9db", "Apache License 2.0", "https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/blob/9217f5db79a29953eb74d5343926648285ec7e67/LICENSE", "Qwen2.5 model; GGUF repository maintained by Qwen"),
        new Model("smollm2-360m-q4km", "SmolLM2-360M-Instruct · Q4_K_M", "mfuntowicz/SmolLM2-360M-Instruct-Q4_K_M-GGUF", "smollm2-360m-instruct-q4_k_m.gguf", "de67c694b3fa2c6e9b45b50f286b2555c5dee2a8", "https://huggingface.co/mfuntowicz/SmolLM2-360M-Instruct-Q4_K_M-GGUF/resolve/de67c694b3fa2c6e9b45b50f286b2555c5dee2a8/smollm2-360m-instruct-q4_k_m.gguf", 270590528L, "8856952e27c65a87618f8347d1d06328c3953af04e8327b6dd1fab6670358fd0", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0", "SmolLM2 model family by HuggingFaceTB; GGUF uploaded/converted by mfuntowicz"),
        new Model("nemotron3-nano-4b-q4km", "NVIDIA Nemotron 3 Nano 4B · Q4_K_M · experimental en móvil", "nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF", "NVIDIA-Nemotron3-Nano-4B-Q4_K_M.gguf", "ba223d14e45525f7fae81db77ea8cabeb2fc6c25", "https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF/resolve/ba223d14e45525f7fae81db77ea8cabeb2fc6c25/NVIDIA-Nemotron3-Nano-4B-Q4_K_M.gguf", 2837072864L, "be5d9a656a51922f24f1f09a759cebb694e1f5d9728bf0ef9f8c972c5a0b5ef2", "NVIDIA Nemotron Open Model License", "https://www.nvidia.com/en-us/agreements/enterprise-software/nvidia-nemotron-open-model-license/", "NVIDIA Corporation · Nemotron 3 Nano 4B · Q4_K_M")
    ));
    public static List<Model> all() { return MODELS; }
    public static Model find(String id) { if (id == null) return null; for (Model model : MODELS) if (model.id.equals(id)) return model; return null; }
}
