"""Link interop vectors: what the PC's own code produces for fixed keys and fixed randomness.

The phone's TypeScript (platform WebCrypto) must reproduce these bytes exactly, and open
what the PC sealed. CI regenerates this file and fails on any difference, so neither side
can drift. Test keys only: they are public on purpose and never used outside tests.

    python3 mobile/tools/link_vectors.py > mobile/tests/fixtures/link-vectors.json
"""
from __future__ import annotations

import hashlib
import json
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "core"))

from isymotron.link import curve, envelope, identity, pairing  # noqa: E402

BASE_U = (9).to_bytes(32, "little")


def test_identity(name: str, label: str) -> dict:
    sign_seed = hashlib.sha256(f"isymotron-mobile test sign {label}".encode()).digest()
    box_priv = hashlib.sha256(f"isymotron-mobile test box {label}".encode()).digest()
    _, sign_pub = curve.ed25519_keygen(sign_seed)
    box_pub = curve.x25519_shared(box_priv, BASE_U)
    return {
        "protocol": identity.PROTOCOL,
        "name": name,
        "office_id": identity.office_id_of(sign_pub),
        "sign": {"x": identity._b64(sign_pub), "d": identity._b64(sign_seed)},
        "box": {"x": identity._b64(box_pub), "d": identity._b64(box_priv)},
    }


def sealed(own: dict, peer: dict, payload: dict, iv: bytes, nonce: bytes, now: float) -> dict:
    queue = [iv, nonce]
    real = os.urandom
    os.urandom = lambda n: queue.pop(0)  # seal() draws the IV (12) and then the nonce (16)
    try:
        return envelope.seal(own, identity.public_card(peer), payload, now=now)
    finally:
        os.urandom = real


def main() -> None:
    phone = test_identity("isytron-telefono", "phone")
    pc = test_identity("isytron-pc", "pc")
    now = 1_790_000_000.0
    nonce_phone = identity._b64(bytes(range(16)))
    nonce_pc = identity._b64(bytes(range(16, 32)))
    payload_to_pc = {"op": "delegate", "title": "Revisar el respaldo", "body": "hola 🐱 ñandú"}
    payload_to_phone = {"ok": True, "task_id": "task-1790000000000-abcd", "note": "listo ✓"}
    vectors = {
        "note": "GENERATED by mobile/tools/link_vectors.py from the PC's link code. Test keys only.",
        "protocol": identity.PROTOCOL,
        "phone": phone,
        "pc": pc,
        "short_code": {
            "nonce_phone": nonce_phone,
            "nonce_pc": nonce_pc,
            "code": pairing.short_code(phone["sign"]["x"], pc["sign"]["x"], nonce_phone, nonce_pc),
        },
        "shared_key_hex": envelope.shared_key(
            phone["office_id"], identity._unb64(phone["box"]["d"]), identity._unb64(pc["box"]["x"]), pc["office_id"]
        ).hex(),
        "phone_to_pc": {
            "now": now,
            "iv": identity._b64(bytes(12)),
            "nonce": identity._b64(bytes([7] * 16)),
            "payload": payload_to_pc,
            "env": sealed(phone, pc, payload_to_pc, bytes(12), bytes([7] * 16), now),
        },
        "pc_to_phone": {
            "now": now,
            "payload": payload_to_phone,
            "env": sealed(pc, phone, payload_to_phone, bytes([1] * 12), bytes([9] * 16), now),
        },
    }
    json.dump(vectors, sys.stdout, indent=2, ensure_ascii=False)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
